### ISSUE TITLE
Check and test

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/build-first-robot#1]
@lesp would you mind checking and testing this resource for me please?

**Comment by lesp** [comment]
Will do
Les

On Wed, Feb 25, 2015 at 8:53 AM, Carrie Anne Philbin <
notifications@github.com> wrote:

> @lesp https://github.com/lesp would you mind checking and testing this
> resource for me please?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/raspberrypilearning/build-first-robot/issues/1.

## 

Les Pounder
http://bigl.es/
@biglesp on Twitter https://twitter.com/biglesp

**Comment by MissPhilbin** [comment]
Hi @lesp I'm making this repo public, please still check it over when you have time. Thanks.

**Comment by MissPhilbin** [comment]
Hi @LornaLynch or @lauraclay could you give this repo a once over? Thanks.

**Comment by lauraclay** [comment]
Hi!

Can take a look in a few hours when I get WiFi, as I'm currently taking a pit stop with some seals at Inverness...

**Comment by LornaLynch** [comment]
It might have to be this evening for me: is that ok?

Lorna Lynch
Raspberry Pi Foundation
www.raspberrypi.orghttp://www.raspberrypi.org

On 17 Jul 2015, at 12:50, lauraclay <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi!

Can take a look in a few hours when I get WiFi, as I'm currently taking a pit stop with some seals at Inverness...

**Comment by lauraclay** [comment]
Have just arrived at civilisation (ie WiFi), so I'll get on it now :)

Laura Clay

Freelance proofreader, copyeditor and writer

https://about.me/lauraclay

**Comment by lauraclay** [comment]
All done, despite WiFI that apparently blows away in strong winds...

**Comment by LornaLynch** [comment]
I've been through pretty much everything except the worksheet, but I'm full
of illness so you might want to double check. Also, I moved the code
document into a code folder: I think I've caught any links to it, but you
might want to check just in case.

Lorna

Lorna Lynch
Copy Editor
Raspberry Pi Foundation
www.raspberrypi.org

**Comment by LornaLynch** [comment]
Phew! Great work in the face of adversity @lauraclay :)

**Comment by caitlynraspberrypi** [comment]
Resource has been archived - I've updated READ ME and I've closed the issue.
